name: Generate contribution chart

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution chart
        uses: yoshi389111/github-profile-3d-contrib@0.8.0
        with:
          username: <USERNAME>
          theme: "github"

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update contribution chart"
          git push
