name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allows manual trigger
  push:
    branches:
      - main                  # Runs on push to main (adjust branch if needed)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake animation (dark theme)
        uses: Platane/snk@v3
        with:
          github_user_name: VaradD21
          svg_out_path: dist/snake.svg
          palette: "github-dark"  

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
